name: Flutter Build IPA (No Codesign)

on:
  workflow_dispatch: # 允许我们手动点击开始按钮

jobs:
  build:
    runs-on: macos-latest # 使用云端 Mac 电脑
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Project Structure
        run: |
          flutter create --org com.yuwenle baby_diary --platforms ios
          cp main.dart baby_diary/lib/main.dart

      - name: Build IPA (No Codesign)
        run: |
          cd baby_diary
          flutter build ipa --no-codesign

      - name: Package Standard TrollStore IPA
        run: |
          # 1. 创建符合苹果和巨魔规范的 Payload 文件夹
          mkdir -p Payload
          
          # 2. 把编译出来的 .app 移动到 Payload 里面
          cp -r baby_diary/build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app Payload/
          
          # 3. 将其更名为“宝贝日记”让手机桌面显示中文
          mv Payload/Runner.app Payload/宝贝日记.app
          
          # 4. 直接把 Payload 文件夹压成二进制 ipa，不嵌套任何多余母目录
          zip -r baby_diary.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore-IPA
          path: baby_diary.ipa
